# Data Grouping

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
cwd = os.getcwd()

#Get File
file = cwd + '/data_source/NBA_POTW.csv'

#Read CSV using Pandas
df = pd.read_csv(file)
df.head(10)

,Age,Conference,Date,Draft Year,Height,Player,Position,Season,Season short,Seasons in league,Team,Weight,Real_value
0,29,NaN,"Apr 14, 1985",1978,6-5,Micheal Ray Richardson,PG,1984-1985,1985,6,New Jersey Nets,189,1.0
1,23,NaN,"Apr 7, 1985",1982,6-6,Derek Smith,SG,1984-1985,1985,2,Los Angeles Clippers,205,1.0
2,28,NaN,"Apr 1, 1985",1979,6-6,Calvin Natt,F,1984-1985,1985,5,Denver Nuggets,220,1.0
3,37,NaN,"Mar 24, 1985",1969,7-2,Kareem Abdul-Jabbar,C,1984-1985,1985,15,Los Angeles Lakers,225,1.0
4,28,NaN,"Mar 17, 1985",1978,6-9,Larry Bird,SF,1984-1985,1985,5,Boston Celtics,220,1.0
5,26,NaN,"Mar 10, 1985",1980,6-4,Darrell Griffith,SG,1984-1985,1985,4,Utah Jazz,190,1.0
6,24,NaN,"Mar 3, 1985",1982,6-3,Sleepy Floyd,PG,1984-1985,1985,2,Golden State Warriors,170,1.0
7,25,NaN,"Feb 24, 1985",1981,6-6,Mark Aguirre,SF,1984-1985,1985,3,Dallas Mavericks,232,1.0
8,25,NaN,"Feb 17, 1985",1979,6-9,Magic Johnson,PG,1984-1985,1985,5,Los Angeles Lakers,255,1.0
9,25,NaN,"Feb 3, 1985",1982,6-7,Dominique Wilkins,SF,1984-1985,1985,2,Atlanta Hawks,200,1.0

In [3]:
#arrange data in ascending manner
df = df.sort_values(by='Seasons in league', ascending=True)
df.head()

,Age,Conference,Date,Draft Year,Height,Player,Position,Season,Season short,Seasons in league,Team,Weight,Real_value
123,24,NaN,"Feb 25, 1990",1987,7-1,David Robinson,C,1989-1990,1990,0,San Antonio Spurs,250,1.0
586,20,West,"Feb 6, 2006",2005,6-0,Chris Paul,PG,2005-2006,2006,0,New Orleans Hornets,175,0.5
256,31,NaN,"Mar 31, 1996",1985,7-3,Arvydas Sabonis,C,1995-1996,1996,0,Portland Trail Blazers,279,1.0
221,20,NaN,"Jan 9, 1994",1993,6-9,Chris Webber,F-C,1993-1994,1994,0,Golden State Warriors,245,1.0
308,21,NaN,"Mar 1, 1998",1997,6-11,Tim Duncan,FC,1997-1998,1998,0,San Antonio Spurs,250,1.0

In [4]:
#arrange data in a descending manner
df = df.sort_values(by='Seasons in league', ascending=False)
df.head()

,Age,Conference,Date,Draft Year,Height,Player,Position,Season,Season short,Seasons in league,Team,Weight,Real_value
968,38,West,"Apr 13, 2015",1997,6-11,Tim Duncan,FC,2014-2015,2015,17,San Antonio Spurs,250,0.5
525,39,East,"Apr 3, 2005",1987,6-7,Reggie Miller,SG,2004-2005,2005,17,Indiana Pacers,185,0.5
399,38,West,"Feb 17, 2002",1985,6-9,Karl Malone,PF,2001-2002,2002,16,Utah Jazz,265,0.5
926,37,West,"Mar 31, 2014",1997,6-11,Tim Duncan,FC,2013-2014,2014,16,San Antonio Spurs,250,0.5
890,34,West,"Feb 25, 2013",1996,6-6,Kobe Bryant,SG,2012-2013,2013,16,Los Angeles Lakers,212,0.5

In [6]:
#Group by qualitative attributes and count
grouped_by_team = df.groupby('Team').count()
grouped_by_team_desc = grouped_by_team.sort_values(by='Team', ascending=False) #descending order
grouped_by_team_desc.head()

,Age,Conference,Date,Draft Year,Height,Player,Position,Season,Season short,Seasons in league,Weight,Real_value
Team,,,,,,,,,,,,
Washington Wizards,23,23,23,23,23,23,23,23,23,23,23,23
Washington Bullets,8,0,8,8,8,8,8,8,8,8,8,8
Utah Jazz,47,15,47,47,47,47,47,47,47,47,47,47
Toronto Raptors,31,27,31,31,31,31,31,31,31,31,31,31
Seattle SuperSonics,20,8,20,20,20,20,20,20,20,20,20,20

In [9]:
df.groupby(['Team', 'Player']).count()

                                        Age  Conference  Date  Draft Year  \
Team               Player
Atlanta Hawks      Al Horford             3           3     3           3
                   Dikembe Mutombo        4           0     4           4
                   Dominique Wilkins      8           0     8           8
                   Glenn Robinson         1           1     1           1
                   Jeff Teague            2           2     2           2
                   Joe Johnson            6           6     6           6
                   Josh Smith             2           2     2           2
                   Kevin Willis           2           0     2           2
                   Paul Millsap           2           2     2           2
                   Shareef Abdur-Rahim    1           1     1           1
                   Steve Smith            1           0     1           1
Boston Celtics     Al Jefferson           1           1     1           1
                   Antoine Walker         2           2     2           2
                   Isaiah Thomas          5           5     5           5
                   Jared Sullinger        1           1     1           1
                   Jordan Crawford        1           1     1           1
                   Kevin Garnett          5           5     5           5
                   Larry Bird             7           0     7           7
                   Paul Pierce           17          16    17          17
                   Rajon Rondo            1           1     1           1
                   Reggie Lewis           1           0     1           1
                   Robert Parish          2           0     2           2
Brooklyn Nets      Brook Lopez            3           3     3           3
                   Deron Williams         1           1     1           1
                   Joe Johnson            1           1     1           1
Charlotte Bobcats  Al Jefferson           2           2     2           2
                   Gerald Wallace         5           5     5           5
                   Jason Richardson       2           2     2           2
                   Kemba Walker           1           1     1           1
                   Stephen Jackson        1           1     1           1
...                                     ...         ...   ...         ...
Utah Jazz          Adrian Dantley         1           0     1           1
                   Al Jefferson           2           2     2           2
                   Andrei Kirilenko       2           2     2           2
                   Bobby Hansen           1           0     1           1
                   Carlos Boozer          4           4     4           4
                   Darrell Griffith       1           0     1           1
                   Deron Williams         3           3     3           3
                   George Hill            1           1     1           1
                   Gordon Hayward         1           1     1           1
                   Jeff Malone            1           0     1           1
                   John Stockton          6           0     6           6
                   Karl Malone           23           1    23          23
                   Mehmet Okur            1           1     1           1
Washington Bullets Bernard King           2           0     2           2
                   Chris Webber           1           0     1           1
                   Jeff Ruland            1           0     1           1
                   Juwan Howard           1           0     1           1
                   Moses Malone           1           0     1           1
                   Pervis Ellison         1           0     1           1
                   Tom McMillen           1           0     1           1
Washington Wizards Antawn Jamison         1           1     1           1
                   Bradley Beal           1           1     1           1
                   Caron Butler           1           1     1           1
                   Gilbert Arenas         7           7     7           7
                   Jerry Stackhouse       1           1     1           1
                   John Wall              7           7     7           7
                   Larry Hughes           1           1     1           1
                   Marcin Gortat          1           1     1           1
                   Michael Jordan         2           2     2           2
                   Richard Hamilton       1           1     1           1

                                        Height  Position  Season  \
Team               Player
Atlanta Hawks      Al Horford                3         3       3
                   Dikembe Mutombo           4         4       4
                   Dominique Wilkins         8         8       8
                   Glenn Robinson            1         1       1
                   Jeff Teague               2         2       2
                   Joe Johnson               6         6       6
                   Josh Smith                2         2       2
                   Kevin Willis              2         2       2
                   Paul Millsap              2         2       2
                   Shareef Abdur-Rahim       1         1       1
                   Steve Smith               1         1       1
Boston Celtics     Al Jefferson              1         1       1
                   Antoine Walker            2         2       2
                   Isaiah Thomas             5         5       5
                   Jared Sullinger           1         1       1
                   Jordan Crawford           1         1       1
                   Kevin Garnett             5         5       5
                   Larry Bird                7         7       7
                   Paul Pierce              17        17      17
                   Rajon Rondo               1         1       1
                   Reggie Lewis              1         1       1
                   Robert Parish             2         2       2
Brooklyn Nets      Brook Lopez               3         3       3
                   Deron Williams            1         1       1
                   Joe Johnson               1         1       1
Charlotte Bobcats  Al Jefferson              2         2       2
                   Gerald Wallace            5         5       5
                   Jason Richardson          2         2       2
                   Kemba Walker              1         1       1
                   Stephen Jackson           1         1       1
...                                        ...       ...     ...
Utah Jazz          Adrian Dantley            1         1       1
                   Al Jefferson              2         2       2
                   Andrei Kirilenko          2         2       2
                   Bobby Hansen              1         1       1
                   Carlos Boozer             4         4       4
                   Darrell Griffith          1         1       1
                   Deron Williams            3         3       3
                   George Hill               1         1       1
                   Gordon Hayward            1         1       1
                   Jeff Malone               1         1       1
                   John Stockton             6         6       6
                   Karl Malone              23        23      23
                   Mehmet Okur               1         1       1
Washington Bullets Bernard King              2         2       2
                   Chris Webber              1         1       1
                   Jeff Ruland               1         1       1
                   Juwan Howard              1         1       1
                   Moses Malone              1         1       1
                   Pervis Ellison            1         1       1
                   Tom McMillen              1         1       1
Washington Wizards Antawn Jamison            1         1       1
                   Bradley Beal              1         1       1
                   Caron Butler              1         1       1
                   Gilbert Arenas            7         7       7
                   Jerry Stackhouse          1         1       1
                   John Wall                 7         7       7
                   Larry Hughes              1         1       1
                   Marcin Gortat             1         1       1
                   Michael Jordan            2         2       2
                   Richard Hamilton          1         1       1

                                        Season short  Seasons in league  \
Team               Player
Atlanta Hawks      Al Horford                      3                  3
                   Dikembe Mutombo                 4                  4
                   Dominique Wilkins               8                  8
                   Glenn Robinson                  1                  1
                   Jeff Teague                     2                  2
                   Joe Johnson                     6                  6
                   Josh Smith                      2                  2
                   Kevin Willis                    2                  2
                   Paul Millsap                    2                  2
                   Shareef Abdur-Rahim             1                  1
                   Steve Smith                     1                  1
Boston Celtics     Al Jefferson                    1                  1
                   Antoine Walker                  2                  2
                   Isaiah Thomas                   5                  5
                   Jared Sullinger                 1                  1
                   Jordan Crawford                 1                  1
                   Kevin Garnett                   5                  5
                   Larry Bird                      7                  7
                   Paul Pierce                    17                 17
                   Rajon Rondo                     1                  1
                   Reggie Lewis                    1                  1
                   Robert Parish                   2                  2
Brooklyn Nets      Brook Lopez                     3                  3
                   Deron Williams                  1                  1
                   Joe Johnson                     1                  1
Charlotte Bobcats  Al Jefferson                    2                  2
                   Gerald Wallace                  5                  5
                   Jason Richardson                2                  2
                   Kemba Walker                    1                  1
                   Stephen Jackson                 1                  1
...                                              ...                ...
Utah Jazz          Adrian Dantley                  1                  1
                   Al Jefferson                    2                  2
                   Andrei Kirilenko                2                  2
                   Bobby Hansen                    1                  1
                   Carlos Boozer                   4                  4
                   Darrell Griffith                1                  1
                   Deron Williams                  3                  3
                   George Hill                     1                  1
                   Gordon Hayward                  1                  1
                   Jeff Malone                     1                  1
                   John Stockton                   6                  6
                   Karl Malone                    23                 23
                   Mehmet Okur                     1                  1
Washington Bullets Bernard King                    2                  2
                   Chris Webber                    1                  1
                   Jeff Ruland                     1                  1
                   Juwan Howard                    1                  1
                   Moses Malone                    1                  1
                   Pervis Ellison                  1                  1
                   Tom McMillen                    1                  1
Washington Wizards Antawn Jamison                  1                  1
                   Bradley Beal                    1                  1
                   Caron Butler                    1                  1
                   Gilbert Arenas                  7                  7
                   Jerry Stackhouse                1                  1
                   John Wall                       7                  7
                   Larry Hughes                    1                  1
                   Marcin Gortat                   1                  1
                   Michael Jordan                  2                  2
                   Richard Hamilton                1                  1

                                        Weight  Real_value
Team               Player
Atlanta Hawks      Al Horford                3           3
                   Dikembe Mutombo           4           4
                   Dominique Wilkins         8           8
                   Glenn Robinson            1           1
                   Jeff Teague               2           2
                   Joe Johnson               6           6
                   Josh Smith                2           2
                   Kevin Willis              2           2
                   Paul Millsap              2           2
                   Shareef Abdur-Rahim       1           1
                   Steve Smith               1           1
Boston Celtics     Al Jefferson              1           1
                   Antoine Walker            2           2
                   Isaiah Thomas             5           5
                   Jared Sullinger           1           1
                   Jordan Crawford           1           1
                   Kevin Garnett             5           5
                   Larry Bird                7           7
                   Paul Pierce              17          17
                   Rajon Rondo               1           1
                   Reggie Lewis              1           1
                   Robert Parish             2           2
Brooklyn Nets      Brook Lopez               3           3
                   Deron Williams            1           1
                   Joe Johnson               1           1
Charlotte Bobcats  Al Jefferson              2           2
                   Gerald Wallace            5           5
                   Jason Richardson          2           2
                   Kemba Walker              1           1
                   Stephen Jackson           1           1
...                                        ...         ...
Utah Jazz          Adrian Dantley            1           1
                   Al Jefferson              2           2
                   Andrei Kirilenko          2           2
                   Bobby Hansen              1           1
                   Carlos Boozer             4           4
                   Darrell Griffith          1           1
                   Deron Williams            3           3
                   George Hill               1           1
                   Gordon Hayward            1           1
                   Jeff Malone               1           1
                   John Stockton             6           6
                   Karl Malone              23          23
                   Mehmet Okur               1           1
Washington Bullets Bernard King              2           2
                   Chris Webber              1           1
                   Jeff Ruland               1           1
                   Juwan Howard              1           1
                   Moses Malone              1           1
                   Pervis Ellison            1           1
                   Tom McMillen              1           1
Washington Wizards Antawn Jamison            1           1
                   Bradley Beal              1           1
                   Caron Butler              1           1
                   Gilbert Arenas            7           7
                   Jerry Stackhouse          1           1
                   John Wall                 7           7
                   Larry Hughes              1           1
                   Marcin Gortat             1           1
                   Michael Jordan            2           2
                   Richard Hamilton          1           1

[349 rows x 11 columns]

In [8]:
#Group Team by group labels i.e Player
grouped_team_by_player = df['Player'].groupby(df['Team']).count()
grouped_team_by_player.head()

Team
Atlanta Hawks        32
Boston Celtics       43
Brooklyn Nets         5
Charlotte Bobcats    11
Charlotte Hornets    15
Name: Player, dtype: int64

## Lambda Functions

In [12]:
from dateutil import parser

df['Date Formatted'] = df['Date'].apply(lambda x: parser.parse(x).strftime('%Y-%m-%d') )

df.sort_values(by='Date Formatted', ascending=True)

,Age,Conference,Date,Draft Year,Height,Player,Position,Season,Season short,Seasons in league,Team,Weight,Real_value,Date Formatted
22,26,NaN,"Nov 4, 1984",1981,6-10,Larry Nance,PF,1984-1985,1985,3,Phoenix Suns,205,1.0,1984-11-04
21,31,NaN,"Nov 11, 1984",1976,6-7,Alex English,SF,1984-1985,1985,8,Denver Nuggets,190,1.0,1984-11-11
20,29,NaN,"Nov 18, 1984",1976,6-10,Moses Malone,C,1984-1985,1985,8,Philadelphia Sixers,215,1.0,1984-11-18
19,28,NaN,"Nov 25, 1984",1977,6-7,Bernard King,SF,1984-1985,1985,7,New York Knicks,205,1.0,1984-11-25
18,29,NaN,"Dec 2, 1984",1977,6-11,Jack Sikma,C,1984-1985,1985,7,Seattle SuperSonics,230,1.0,1984-12-02
17,25,NaN,"Dec 9, 1984",1981,6-9,Orlando Woolridge,PF,1984-1985,1985,3,Chicago Bulls,215,1.0,1984-12-09
16,23,NaN,"Dec 16, 1984",1982,6-6,Derek Smith,SG,1984-1985,1985,2,Los Angeles Clippers,205,1.0,1984-12-16
15,23,NaN,"Dec 23, 1984",1982,6-9,Terry Cummings,PF,1984-1985,1985,2,Milwaukee Bucks,220,1.0,1984-12-23
14,29,NaN,"Dec 30, 1984",1978,6-5,Micheal Ray Richardson,PG,1984-1985,1985,6,New Jersey Nets,189,1.0,1984-12-30
13,23,NaN,"Jan 6, 1985",1981,6-1,Isiah Thomas,PG,1984-1985,1985,3,Detroit Pistons,180,1.0,1985-01-06
12,31,NaN,"Jan 13, 1985",1975,6-2,World B. Free,G,1984-1985,1985,9,Cleveland Cavaliers,185,1.0,1985-01-13
11,22,NaN,"Jan 20, 1985",1984,6-6,Michael Jordan,SG,1984-1985,1985,0,Chicago Bulls,215,1.0,1985-01-20
10,32,NaN,"Jan 27, 1985",1974,6-11,Tom McMillen,PF,1984-1985,1985,9,Washington Bullets,215,1.0,1985-01-27
9,25,NaN,"Feb 3, 1985",1982,6-7,Dominique Wilkins,SF,1984-1985,1985,2,Atlanta Hawks,200,1.0,1985-02-03
8,25,NaN,"Feb 17, 1985",1979,6-9,Magic Johnson,PG,1984-1985,1985,5,Los Angeles Lakers,255,1.0,1985-02-17
7,25,NaN,"Feb 24, 1985",1981,6-6,Mark Aguirre,SF,1984-1985,1985,3,Dallas Mavericks,232,1.0,1985-02-24
6,24,NaN,"Mar 3, 1985",1982,6-3,Sleepy Floyd,PG,1984-1985,1985,2,Golden State Warriors,170,1.0,1985-03-03
5,26,NaN,"Mar 10, 1985",1980,6-4,Darrell Griffith,SG,1984-1985,1985,4,Utah Jazz,190,1.0,1985-03-10
4,28,NaN,"Mar 17, 1985",1978,6-9,Larry Bird,SF,1984-1985,1985,5,Boston Celtics,220,1.0,1985-03-17
3,37,NaN,"Mar 24, 1985",1969,7-2,Kareem Abdul-Jabbar,C,1984-1985,1985,15,Los Angeles Lakers,225,1.0,1985-03-24
2,28,NaN,"Apr 1, 1985",1979,6-6,Calvin Natt,F,1984-1985,1985,5,Denver Nuggets,220,1.0,1985-04-01
1,23,NaN,"Apr 7, 1985",1982,6-6,Derek Smith,SG,1984-1985,1985,2,Los Angeles Clippers,205,1.0,1985-04-07
0,29,NaN,"Apr 14, 1985",1978,6-5,Micheal Ray Richardson,PG,1984-1985,1985,6,New Jersey Nets,189,1.0,1985-04-14
45,24,NaN,"Nov 3, 1985",1982,6-6,Derek Smith,SG,1985-1986,1986,3,Los Angeles Clippers,205,1.0,1985-11-03
44,25,NaN,"Nov 10, 1985",1981,6-8,Buck Williams,PF,1985-1986,1986,4,New Jersey Nets,215,1.0,1985-11-10
43,23,NaN,"Nov 17, 1985",1985,7-0,Patrick Ewing,C,1985-1986,1986,0,New York Knicks,240,1.0,1985-11-17
42,32,NaN,"Nov 24, 1985",1976,6-7,Alex English,SF,1985-1986,1986,9,Denver Nuggets,190,1.0,1985-11-24
41,29,NaN,"Dec 1, 1985",1978,6-9,Larry Bird,SF,1985-1986,1986,6,Boston Celtics,220,1.0,1985-12-01
40,27,NaN,"Dec 8, 1985",1980,6-10,Jeff Ruland,C,1985-1986,1986,4,Washington Bullets,240,1.0,1985-12-08
39,23,NaN,"Dec 15, 1985",1984,6-3,Alvin Robertson,SG,1985-1986,1986,1,San Antonio Spurs,185,1.0,1985-12-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1127,33,East,"Dec 18, 2017",2003,203cm,LeBron James,F,2017-2018,2018,14,Cleveland Cavaliers,113kg,0.5,2017-12-18
1128,32,West,"Dec 18, 2017",2005,183cm,Chris Paul,PG,2017-2018,2018,12,Houston Rockets,79kg,0.5,2017-12-18
1125,28,East,"Dec 26, 2017",2009,201cm,DeMar DeRozan,GF,2017-2018,2018,8,Toronto Raptors,100kg,0.5,2017-12-26
1126,29,West,"Dec 26, 2017",2008,191cm,Russell Westbrook,G,2017-2018,2018,9,Oklahoma City Thunder,91kg,0.5,2017-12-26
1124,31,West,"Jan 2, 2018",2005,185cm,Lou Williams,G,2017-2018,2018,12,Los Angeles Clippers,79kg,0.5,2018-01-02
1123,24,East,"Jan 2, 2018",2012,196cm,Bradley Beal,SG,2017-2018,2018,5,Washington Wizards,94kg,0.5,2018-01-02
1121,28,East,"Jan 8, 2018",2009,201cm,DeMar DeRozan,GF,2017-2018,2018,8,Toronto Raptors,100kg,0.5,2018-01-08
1122,29,West,"Jan 8, 2018",2009,191cm,Stephen Curry,G,2017-2018,2018,8,Golden State Warriors,86kg,0.5,2018-01-08
1120,31,West,"Jan 15, 2018",2005,185cm,Lou Williams,G,2017-2018,2018,12,Los Angeles Clippers,79kg,0.5,2018-01-15
1119,31,East,"Jan 15, 2018",2008,191cm,Goran Dragic,G,2017-2018,2018,9,Miami Heat,86kg,0.5,2018-01-15
1117,23,East,"Jan 22, 2018",2014,213cm,Joel Embiid,C,2017-2018,2018,3,Philadelphia Sixers,113kg,0.5,2018-01-22
1118,27,West,"Jan 22, 2018",2012,191cm,Damian Lillard,G,2017-2018,2018,5,Portland Trail Blazers,88kg,0.5,2018-01-22
1116,29,West,"Jan 29, 2018",2009,191cm,Stephen Curry,G,2017-2018,2018,8,Golden State Warriors,86kg,0.5,2018-01-29
1115,26,East,"Jan 29, 2018",2012,203cm,Khris Middleton,SF,2017-2018,2018,5,Milwaukee Bucks,106kg,0.5,2018-01-29
1113,24,East,"Feb 5, 2018",2012,211cm,Andre Drummond,C,2017-2018,2018,5,Detroit Pistons,127kg,0.5,2018-02-05
1114,28,West,"Feb 5, 2018",2009,196cm,James Harden,SG,2017-2018,2018,8,Houston Rockets,100kg,0.5,2018-02-05
1112,28,West,"Feb 12, 2018",2009,196cm,James Harden,SG,2017-2018,2018,8,Houston Rockets,100kg,0.5,2018-02-12
1111,23,East,"Feb 12, 2018",2014,213cm,Joel Embiid,C,2017-2018,2018,3,Philadelphia Sixers,113kg,0.5,2018-02-12
1110,24,West,"Mar 5, 2018",2012,208cm,Anthony Davis,PF,2017-2018,2018,5,New Orleans Pelicans,115kg,0.5,2018-03-05
1109,28,East,"Mar 5, 2018",2009,201cm,DeMar DeRozan,GF,2017-2018,2018,8,Toronto Raptors,100kg,0.5,2018-03-05
1107,28,East,"Mar 12, 2018",2009,201cm,DeMar DeRozan,GF,2017-2018,2018,8,Toronto Raptors,100kg,0.5,2018-03-12
1108,27,West,"Mar 12, 2018",2012,191cm,Damian Lillard,G,2017-2018,2018,5,Portland Trail Blazers,88kg,0.5,2018-03-12
1105,33,East,"Mar 19, 2018",2003,203cm,LeBron James,F,2017-2018,2018,14,Cleveland Cavaliers,113kg,0.5,2018-03-19
1106,29,West,"Mar 19, 2018",2008,191cm,Russell Westbrook,G,2017-2018,2018,9,Oklahoma City Thunder,91kg,0.5,2018-03-19
1103,33,East,"Mar 26, 2018",2003,203cm,LeBron James,F,2017-2018,2018,14,Cleveland Cavaliers,113kg,0.5,2018-03-26
1104,32,West,"Mar 26, 2018",2006,211cm,LaMarcus Aldridge,FC,2017-2018,2018,11,San Antonio Spurs,118kg,0.5,2018-03-26
1101,25,East,"Apr 2, 2018",2013,193cm,Victor Oladipo,G,2017-2018,2018,4,Indiana Pacers,95kg,0.5,2018-04-02
1102,27,West,"Apr 2, 2018",2012,191cm,Damian Lillard,G,2017-2018,2018,5,Portland Trail Blazers,88kg,0.5,2018-04-02
1100,23,West,"Apr 9, 2018",2014,208cm,Nikola Jokic,C,2017-2018,2018,2,Denver Nuggets,113kg,0.5,2018-04-09
1099,21,East,"Apr 9, 2018",2016,208cm,Ben Simmons,PF,2017-2018,2018,1,Philadelphia Sixers,104kg,0.5,2018-04-09

In [17]:
group_by_team = df.groupby(['Team'])
group_by_team.size()

Team
Atlanta Hawks             32
Boston Celtics            43
Brooklyn Nets              5
Charlotte Bobcats         11
Charlotte Hornets         15
Chicago Bulls             44
Cleveland Cavaliers       59
Dallas Mavericks          30
Denver Nuggets            41
Detroit Pistons           29
Golden State Warriors     44
Houston Rockets           56
Indiana Pacers            23
Los Angeles Clippers      27
Los Angeles Lakers        71
Memphis Grizzlies          9
Miami Heat                57
Milwaukee Bucks           26
Minnesota Timberwolves    26
New Jersey Nets           31
New Orleans Hornets       12
New Orleans Pelicans       5
New York Knicks           36
Oklahoma City Thunder     41
Orlando Magic             44
Philadelphia Sixers       37
Phoenix Suns              45
Portland Trail Blazers    33
Sacramento Kings          23
San Antonio Spurs         61
Seattle SuperSonics       20
Toronto Raptors           31
Utah Jazz                 47
Washington Bullets         8
Washington Wizards        23
dtype: int64

In [18]:
group_by_teamdf = df.groupby(['Team', 'Date Formatted'])
group_by_teamdf.size()

Team                Date Formatted
Atlanta Hawks       1985-02-03        1
                    1985-12-29        1
                    1986-04-13        1
                    1986-12-14        1
                    1987-12-27        1
                    1988-01-17        1
                    1988-02-14        1
                    1991-01-06        1
                    1991-11-24        1
                    1994-03-27        1
                    1996-12-01        1
                    1997-11-09        1
                    1998-01-11        1
                    1999-02-07        1
                    2000-01-31        1
                    2001-11-25        1
                    2002-11-03        1
                    2005-12-19        1
                    2006-11-12        1
                    2007-12-09        1
                    2007-12-23        1
                    2008-04-06        1
                    2009-11-09        1
                    2012-03-26        1
                    2012-11-26        1
                    2012-12-10        1
                    2014-01-27        1
                    2014-04-14        1
                    2014-12-22        1
                    2015-01-05        1
                                     ..
Washington Bullets  1985-12-08        1
                    1987-02-22        1
                    1988-01-31        1
                    1991-01-13        1
                    1991-12-22        1
                    1996-04-14        1
                    1997-04-20        1
Washington Wizards  2001-12-16        1
                    2002-11-10        1
                    2003-01-05        1
                    2003-03-02        1
                    2004-12-05        1
                    2005-01-16        1
                    2005-11-14        1
                    2006-02-13        1
                    2006-02-27        1
                    2006-12-10        1
                    2006-12-17        1
                    2007-01-07        1
                    2007-01-21        1
                    2008-03-16        1
                    2013-03-18        1
                    2013-11-25        1
                    2014-03-03        1
                    2014-12-15        1
                    2015-12-28        1
                    2016-01-18        1
                    2017-01-02        1
                    2017-03-13        1
                    2018-01-02        1
Length: 1144, dtype: int64

In [20]:
#counts the number of times the player's name has been found 
df['Player'].value_counts()

LeBron James           61
Kobe Bryant            33
Kevin Durant           26
Michael Jordan         25
Karl Malone            23
Allen Iverson          23
Tim Duncan             23
Kevin Garnett          20
Shaquille O'Neal       20
Dwyane Wade            19
James Harden           18
Dwight Howard          18
Carmelo Anthony        18
Russell Westbrook      17
Jason Kidd             17
Paul Pierce            17
Dirk Nowitzki          16
David Robinson         15
Chris Paul             13
Patrick Ewing          12
Tracy McGrady          12
Magic Johnson          12
Stephen Curry          12
Hakeem Olajuwon        12
Clyde Drexler          11
Charles Barkley        11
Vince Carter           11
DeMar DeRozan          10
LaMarcus Aldridge      10
Chris Webber            9
                       ..
Herb Williams           1
Andrew Bogut            1
Nate Robinson           1
Derek Anderson          1
Drew Gooden             1
Armen Gilliam           1
Vlade Divac             1
Hot Rod Williams        1
Buck Williams           1
Nicolas Batum           1
George Hill             1
Kristaps Porzingis      1
Nikola Vucevic          1
Sidney Moncrief         1
Cuttino Mobley          1
Juwan Howard            1
Julius Erving           1
Kenyon Martin           1
Caron Butler            1
Terry Mills             1
Roy Tarpley             1
Kareem Abdul-Jabbar     1
Tom McMillen            1
Mark Jackson            1
Antawn Jamison          1
Mike James              1
Bobby Hansen            1
Kenneth Faried          1
David West              1
Hassan Whiteside        1
Name: Player, Length: 274, dtype: int64