# Pivoting

## Deriving a new table from a existing one

* Specify index or indices to pivot on
* data is reshaped based on column values

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
#file path
cwd = os.getcwd()

#file
file = cwd + '/data_source/vgsales.csv'

#Dataframe
vgs = pd.read_csv(file)
vgs.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [3]:
vgsp = pd.pivot_table(vgs, index=['Rank','Name', 'Year'])
vgsp.head()

,,,EU_Sales,Global_Sales,JP_Sales,NA_Sales,Other_Sales
Rank,Name,Year,,,,,
1,Wii Sports,2006.0,29.02,82.74,3.77,41.49,8.46
2,Super Mario Bros.,1985.0,3.58,40.24,6.81,29.08,0.77
3,Mario Kart Wii,2008.0,12.88,35.82,3.79,15.85,3.31
4,Wii Sports Resort,2009.0,11.01,33.00,3.28,15.75,2.96
5,Pokemon Red/Pokemon Blue,1996.0,8.89,31.37,10.22,11.27,1.00

In [4]:
vgsp2 = pd.pivot_table(vgs, index=['Rank','Name', 'Year'], values=['EU_Sales', 'JP_Sales'])
vgsp2.head()

                                      EU_Sales  JP_Sales
Rank Name                     Year
1    Wii Sports               2006.0     29.02      3.77
2    Super Mario Bros.        1985.0      3.58      6.81
3    Mario Kart Wii           2008.0     12.88      3.79
4    Wii Sports Resort        2009.0     11.01      3.28
5    Pokemon Red/Pokemon Blue 1996.0      8.89     10.22

## Apply functions

In [39]:
vgsf = vgs[(vgs.Year >= 2008) & (vgs.Year <= 2013)]
vgsp3 = pd.pivot_table(vgsf, index=['Name'], values=['EU_Sales', 'JP_Sales'], aggfunc=np.sum)
vgsp3 = vgsp3.sort_values(by='Name', ascending=True)
vgsp3.head(1370)

                                                    EU_Sales  JP_Sales
Name
.hack//Link                                             0.00      0.14
.hack: Sekai no Mukou ni + Versus                       0.00      0.03
007: Quantum of Solace                                  1.35      0.04
1 vs. 100                                               0.00      0.00
1/2 Summer +                                            0.00      0.01
10 Minute Solution                                      0.01      0.00
100 All-Time Favorites                                  0.12      0.00
100 Classic Books                                       0.52      0.00
100 Classic Games                                       0.03      0.00
1000 Cooking Recipes from ELLE à table                  0.02      0.00
1001 Touch Games                                        0.17      0.00
101-in-1 Explosive Megamix                              0.13      0.00
101-in-1 Party Megamix Wii                              0.01      0.00
101-in-1 Sports Megamix                                 0.00      0.00
101-in-1 Sports Party Megamix                           0.00      0.00
11eyes: CrossOver                                       0.00      0.04
12Riven: The Psi-Climinal of Integral                   0.00      0.04
15 Days                                                 0.01      0.00
18 Wheels of Steel: Extreme Trucker                     0.02      0.00
18 Wheels of Steel: Extreme Trucker 2                   0.02      0.00
2 in 1 Combo Pack: Sonic Heroes / Super Monkey ...      0.01      0.00
2010 FIFA World Cup South Africa                        1.46      0.13
3 in 1: Solitaire, Mahjong & Tangram                    0.07      0.00
3D Dot Game Heroes                                      0.12      0.03
4 Elements                                              0.04      0.00
428: Fuusa Sareta Shibuya de                            0.00      0.19
50 Cent: Blood on the Sand                              0.13      0.01
50 Classic Games                                        0.02      0.00
7 Wonders II                                            0.15      0.00
7 Wonders: Treasures of Seven                           0.03      0.00
...                                                      ...       ...
Gold's Gym: Dance Workout                               0.11      0.00
Golden Axe: Beast Rider                                 0.25      0.00
Golden Sun: Dark Dawn                                   0.11      0.13
GoldenEye 007 (2010)                                    0.74      0.13
Goldeneye 007: Reloaded                                 0.56      0.00
Gon: BakuBakuBakuBaku Adventure                         0.00      0.02
Goodbye Deponia                                         0.06      0.00
Goosebumps HorrorLand                                   0.03      0.00
Gormiti: The Lords of Nature!                           0.00      0.00
Gourmet Chef: Cook Your Way to Fame                     0.00      0.00
Gran Turismo (PSP)                                      1.59      0.31
Gran Turismo 5                                          4.88      0.81
Gran Turismo 6                                          1.80      0.40
Grand Knights History                                   0.00      0.13
Grand Slam Tennis 2                                     0.18      0.00
Grand Theft Auto IV                                     7.65      0.58
Grand Theft Auto V                                     14.58      1.03
Grand Theft Auto: Chinatown Wars                        1.07      0.08
Grand Theft Auto: San Andreas                           0.03      0.00
Gravity Rush                                            0.20      0.09
Gray Matter                                             0.09      0.00
Grease                                                  0.25      0.00
Grease Dance                                            0.05      0.00
Great Battle Full Blast                                 0.00      0.04
Great Party Games                                       0.08      0.00
Green Day: Rock Band                                    0.41      0.00
Green Lantern: Rise of the Manhunters                   0.19      0.00
Greg Hastings Paintball 2                               0.00      0.00
Grey's Anatomy: The Video Game                          0.04      0.00
Grisaia no Kajitsu: La Fruit de la Grisaia              0.00      0.01

[1370 rows x 2 columns]